#ifndef TIPOS_H
#define TIPOS_H

typedef enum {
  TR_PROGRAMA,
  TR_DECLARACION_LIST,
  TR_DECLARACION,
  TR_METHOD,
  TR_EXPRESION,
  TR_METHOD_EXTERN,
  TR_BLOCK,
  TR_INVOCATION,
  TR_IF_STATEMENT,
  TR_IF_ELSE_STATEMENT,
  TR_PARAM_LIST,
  TR_PARAM,
  TR_ARG_LIST,
  TR_ARG,
  TR_IDENTIFICADOR,
  TR_SUMA,
  TR_MULTIPLICACION,
  TR_AND,
  TR_OR,
  TR_LISTA_SENTENCIAS,
  TR_ASIGNACION,

  TR_RETURN,
  TR_VALOR,
} TipoNodo;

typedef enum { T_INT, T_BOOL, T_VOID } Tipos;

#endif // TIPOS_H
