#ifndef TIPOS_H
#define TIPOS_H

typedef enum {
  TR_PROGRAMA,
  TR_METHOD_DECLARATION,
  TR_VAR_DECLARATION,
  TR_DECLARATION_LIST,
  TR_METHOD_DECLARATION_EXTERN,
  TR_EXPRESION,
  TR_BLOCK,
  TR_INVOCATION,
  TR_IF_STATEMENT,
  TR_IF_ELSE_STATEMENT,
  TR_WHILE_STATEMENT,
  TR_PARAM_LIST,
  TR_PARAM,
  TR_ARG_LIST,
  TR_ARG,
  TR_IDENTIFICADOR,
  TR_SUMA,
  TR_MULTIPLICACION,
  TR_AND,
  TR_OR,
  TR_LISTA_SENTENCIAS,
  TR_ASIGNACION,
  TR_NEGACION_ARITMETICA,
  TR_NEGACION_LOGICA,
  TR_RESTA,
  TR_DIVICION,
  TR_MODULO,
  TR_MENOR,
  TR_MAYOR,
  TR_IGUAL_LOGICO,
  TR_RETURN,
  TR_VALOR,
} TipoNodo;

typedef enum { T_INT, T_BOOL, T_VOID } Tipos;

typedef enum { S_VAR, S_FUNC } Categoria;

#endif // TIPOS_H
