#ifndef TYPES_H
#define TYPES_H

typedef enum {
  TR_PROGRAM,
  TR_METHOD_DECLARATION,
  TR_EXTERN,
  TR_VAR_DECLARATION,
  TR_PARAM,
  TR_PARAM_LIST,
  TR_BLOCK,
  TR_ASSIGN,
  TR_INVOCATION,
  TR_IF_STATEMENT,
  TR_ELSE_BODY,
  TR_WHILE_STATEMENT,
  TR_RETURN,
  TR_LOGIC_NEGATION,
  TR_ARITHMETIC_NEGATION,
  TR_ADDITION,
  TR_SUBSTRACTION,
  TR_MULTIPLICATION,
  TR_DIVITION,
  TR_MODULO,
  TR_LESS_THAN,
  TR_GREATER_THAN,
  TR_LOGIC_EQUAL,
  TR_AND,
  TR_OR,
  TR_IDENTIFIER,
  TR_VALUE,
  TR_ARG_LIST,

  TR_DECLARATION_LIST,
  TR_SENTENCES_LIST
} TipoNodo;

typedef enum { T_INT, T_BOOL, T_VOID } Tipos;

typedef enum { S_VAR, S_FUNC } Categoria;

#endif // TYPES_H
