#ifndef TYPES_H
#define TYPES_H

typedef enum {
  TR_PROGRAMA,
  TR_DECLARATION_LIST,
  TR_DECLARACION,
  TR_PERFIL,
  TR_EXPRESION,
  TR_PERFIL_EXTERN,
  TR_BLOCK,
  TR_INVOCATION,
  TR_IF_STATEMENT,
  TR_IF_ELSE_STATEMENT,
  TR_WHILE_STATEMENT,
  TR_LISTA_SENTENCIAS,
  TTR_PARAM_LIST,
  TR_ASIGNACION,
  TR_ARG_LIST,
  TR_RETURN,
  TR_VALOR,
  TR_IDENTIFICADOR,
  TR_NEGATIVE_NUMBER,
  TR_NEGATION,
  TR_SUMA,
  TR_SUBSTRACTION,
  TR_MULTIPLICACION,
  TR_DIVISION,
  TR_MODULO,
  TR_LESS_THAN,
  TR_GREATER_THAN,
  TR_EQ,
  TR_AND,
  TR_OR
} TipoNodo;

typedef enum { T_INT, T_BOOL, T_VOID } Tipos;

#endif // TYPES_H
